# Generated by Django 2.2.6 on 2021-06-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('eta', models.PositiveIntegerField()),
                ('lati', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longi', models.DecimalField(decimal_places=6, max_digits=9)),
                ('paused', models.BooleanField()),
                ('ended', models.BooleanField()),
                ('allusers', models.ManyToManyField(related_name='allqueues', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
