# Generated by Django 2.2.6 on 2021-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20210616_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
