# Generated by Django 2.2.6 on 2021-06-15 17:33

from django.conf import settings
from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_auto_20210616_0028'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='queue',
            name='allusers',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='allqueues', to=settings.AUTH_USER_MODEL),
        ),
        AlterSortedManyToManyField(
            model_name='queue',
            name='users',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
