# Generated by Django 2.2.6 on 2021-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_auto_20210616_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='lati',
            field=models.DecimalField(decimal_places=600, max_digits=600),
        ),
        migrations.AlterField(
            model_name='queue',
            name='longi',
            field=models.DecimalField(decimal_places=600, max_digits=600),
        ),
    ]
