# Generated by Django 2.2.6 on 2021-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_auto_20210616_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
